[sdk/python] task: align python sdk with small changes in javascript sdk
symbol/symbol pull request #102
Opened 2022-02-10 20:24 UTC by Jaguar0625

## What is the current behavior?
small differences between py and js sdk were introduced by #89

## What's the issue?
this is confusing for users

## How have you changed the behavior?
i have aligned the py sdk behavior with the js sdk

## How was this change tested?
yes

2022-02-10 20:40 UTC, gimre-xymcity requested changes

2022-02-10 20:40 UTC, gimre-xymcity commented on sdk/python/tests/test_BaseValue.py
> +		self.assertEqual('0x543210FEDCBA9877', str(BaseValue(WORD_WIDTH, HIBIT_SET_VALUE_SIGNED, None, True)))
this certainly is not js behavior :D

2022-02-11 21:01 UTC, Jaguar0625 commented on sdk/python/tests/test_BaseValue.py
> +		self.assertEqual('0x543210FEDCBA9877', str(BaseValue(WORD_WIDTH, HIBIT_SET_VALUE_SIGNED, None, True)))
fixed

2022-02-14 13:10 UTC, gimre-xymcity approved these changes

2022-02-14 14:34 UTC, merged