[jenkins] fix: cd pipeline agent is separated to support non-container agent
symbol/symbol pull request #148
Opened 2022-02-28 10:59 UTC by yilmazbahadir

CI and CD used to be running in the same Docker container but in the CD part, docker build and publishing was failing
due to `docker: not found` error. In order to avoid a `docker-in-docker` solution, it has been decided to run CD pipeline in a non-container agent.

## **The details asked below will be provided soon**

> Note: This is the default pull request template.

## What is the current behavior?
> * Describe the current behavior of the application or program.
> * Please mention any related issue numbers.

## What's the issue?
> * Explain in detail why this behavior is an issue - and why this should be changed.

## How have you changed the behavior?
> * Describe your changes in detail for the maintainer.
> * Explain the solution you have provided, and *how* it fixes the issue case.
> * Specify if this is a *breaking change*.

## How was this change tested?
> * Were unit test cases or end-to-end test cases included in this fix, or was only manual testing applicable?
> * Please provide a detailed description of test cases included or updated.
> * Does this change introduce any new warnings or binding errors? If so, make sure to update the relevant documentation and reference this pull request.

---- 

## Requirements

> Your pull request must pass these requirements in order to be accepted. You can delete this section upon submitting your pull request.

* [ ] My pull request title is prefixed with the directory and subdirectory it affects.
* [ ] My pull request contains a single change or feature.
* [ ] My commits are clearly labeled with one of the following: **feat | bug | fix | build | perf | task**
* [ ] My code has been linted.
* [ ] My code has comments, particularly in any hard to understand areas.
* [ ] My code follows the style guidelines.
* [ ] I have written and supplied test cases (either unit tests or end-to-end, where relevant).
* [ ] I have made any corresponding changes to the documentation (where relevant).

2022-02-28 19:27 UTC, Wayonb requested changes

2022-02-28 20:12 UTC, yilmazbahadir commented on jenkins/shared-library/vars/defaultCiPipeline.groovy
> +					label ${ params.cdPipelineAgent :? env.DEFAULT_CD_PIPELINE_AGENT }
Hmm, didn't know that, perfect! Added `reuseNode: true` to enable that. Updated!

2022-02-28 20:13 UTC, yilmazbahadir commented on jenkins/shared-library/vars/defaultCiPipeline.groovy
> +			DEFAULT_CD_PIPELINE_AGENT = 'ubuntu-test'
Removed after the new approach.

2022-03-01 04:15 UTC, Wayonb approved these changes
Looks good

2022-03-01 14:35 UTC, Jaguar0625 approved these changes

2022-03-01 14:41 UTC, merged